import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const quickSand = Quicksand({
  variable: "--font-QuickSand",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Nexergy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={quickSand.variable}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
