import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const montserratAlternates = Montserrat_Alternates({
  variable: "--font-Montserrat-Alternates",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  display: "swap"
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Nexergy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserratAlternates.variable}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
